### ISSUE TITLE
Do this FadeLed have "disable" flag? 

### ISSUE THREAD

**Issue by ldicdican** [septillion-git/FadeLed#29]
I'm just wondering if I can disable the fading and just turn off the LED's, any idea how to disable/stop the process on runtime?

**Comment by septillion-git** [comment]
If you want to stop a fade and turn off the led's immediately you can use:
```C++
led.stop();
led.begin(0);
```

**Comment by ldicdican** [comment]
Thanks, will try this.

More power!
