### ISSUE TITLE
const uint16_t FadeLedGammaTable[101]  in FadeLedGamma.h 

### ISSUE THREAD

**Issue by machliang** [septillion-git/FadeLed#9]
Hi, 
    This is a nice project, thanks~
    While I am trying to compile the example for my ESP8266(10 bit PWM resolution) , 
    here was a compilation error :

Arduino/libraries/FadeLed/src/FadeLed.cpp:13:45: error: cannot convert 'const uint16_t* {aka const short unsigned int*}' to 'const flvar_t* {aka const unsigned int*}' in initialization
                             _biggestStep(100){

    After some experiments and source code tracing, I suggest to update the lines in FadeLedGamma.h :
          const uint16_t FadeLedGammaTable[101] PROGMEM = {....
                         to 
          const flvar_t FadeLedGammaTable[101] PROGMEM = {....
                if FADE_LED_PWM_BITS >= 9
    to avoid the compilation error. 
    Thanks a lot!
                         Mars Liang

**Comment by septillion-git** [comment]
I will look into it 😃 I'm really a AVR user and didn't test the latest version on a ESP.

Thanks for telling me!

**Comment by machliang** [comment]
You are welcome~
